### Get All Employees
GET {{url}}/rest-client
Content-Type: */*

### Add Employee
POST {{url}}/rest-client
Content-Type: application/json

{
  "department": {
    "departmentName": "CS",
    "id": 51
  },
  "name": "Alaa Soliman Badri",
  "position": "Software developer"
}

### Delete Employee by ID
DELETE {{url}}/rest-client/251


### Get Employee by ID
GET {{url}}/rest-client/251

### Update Postion for Emplyee By ID
PUT {{url}}/rest-client/251

Sr.Software Engineer

