---
openapi: 3.0.3
info:
  title: Rest-Client Microservice
  description: Service-Two which consumes Service-One
  version: "1.0"
paths:
  /rest-client:
    get:
      tags:
      - Rest Client Resource
      summary: Get All Employees
      description: 'Return all employees '
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
    post:
      tags:
      - Rest Client Resource
      summary: Add Employee
      description: Return created response for added new employee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        "200":
          description: OK
          content:
            application/json: {}
  /rest-client/{id}:
    get:
      tags:
      - Rest Client Resource
      summary: Get Employees By Id
      description: 'Return employee by it''s id '
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
    put:
      tags:
      - Rest Client Resource
      summary: Update Employee position by it's id
      description: 'Return all employees '
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
    delete:
      tags:
      - Rest Client Resource
      summary: Remove Employee
      description: Return boolean response
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: boolean
components:
  schemas:
    Department:
      type: object
      properties:
        id:
          format: int64
          type: integer
        departmentName:
          type: string
    Employee:
      type: object
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        position:
          type: string
        department:
          $ref: '#/components/schemas/Department'
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
