### Get All Employees
GET {{url}}/employees
Content-Type: */*

### Add Employee
POST {{url}}/employees

{
    "name": "Hady",
    "position": "Software developer",
    "department": {
    "id":51,
    "departmentName": "CS"
  }
}

### Delete Employee by ID
DELETE {{url}}/employees/1


### Get Employee by ID
GET {{url}}/employees/51

### Update Postion for Emplyee By ID
PUT {{url}}/employees/51

Sr.Software Engineer

